---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ory
resources:
  - ./hr.yaml
  - ./ingress.yaml
  - ./rule.yaml
# configMapGenerator:
#   # - name: oath-config
#   #   files:
#   #     - ./config.yaml
#   - name: oath-access-rules
#     files:
#       - ./access-rules.yaml
# generatorOptions:
#   disableNameSuffixHash: true
#   annotations:
#     kustomize.toolkit.fluxcd.io/substitute: disabled
