apiVersion: oathkeeper.ory.sh/v1alpha1
kind: Rule
metadata:
  name: backend-service-rule
  namespace: ory
spec:
  upstream:
    url: "https://google.com"
    preserveHost: true
  match:
    ## My usecase calls for all the other routes to be authenticated, you can change this to other routes instead of regex negative lookahead
    url: "https://proxy-home.dirt.skin"
    methods:
      - GET
      - POST
      - PUT
      - DELETE
      - PATCH
  authenticators:
    - handler: noop
  authorizer:
    handler: allow
  mutators:
    - handler: noop
