---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dev-system
resources:
  - ./helmrelease.yaml
  - ./repo.yaml
  - ./httproute.yaml
  - ./netpol.yaml
