# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/cilium.io/ciliumnetworkpolicy_v2.json
---
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: headlamp
spec:
  description: "Network policy for Headlamp"
  endpointSelector:
    matchLabels:
      app.kubernetes.io/name: headlamp
  ingress:
    # Allow all ingress to headlamp
    - fromEntities:
        - cluster
        - host
        - world
  egress:
    # Allow all egress temporarily for debugging OIDC timeout
    - toEntities:
        - all
