# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/cilium.io/ciliumnetworkpolicy_v2.json
---
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: headlamp
spec:
  description: "Network policy for Headlamp"
  endpointSelector:
    matchLabels:
      app.kubernetes.io/name: headlamp
  ingress:
    # Allow all ingress to headlamp
    - fromEntities:
        - cluster
        - host
        - world
  egress:
    # Allow same namespace traffic
    - toEndpoints:
        - matchLabels:
            io.kubernetes.pod.namespace: dev-system
    # Allow kube-apiserver access
    - toEntities:
        - kube-apiserver
    # Allow egress to ingress/gateway proxy for zitadel OIDC routing
    - toCIDR:
        - "10.0.0.0/8"
      toPorts:
        - ports:
            - port: "443"
              protocol: TCP
            - port: "80"
              protocol: TCP
    - toEntities:
        - world
        - host
      toPorts:
        - ports:
            - port: "443"
              protocol: TCP
            - port: "80"
              protocol: TCP
    - toEndpoints:
        - matchLabels:
            io.kubernetes.pod.namespace: network
      toPorts:
        - ports:
            - port: "443"
              protocol: TCP
            - port: "80"
              protocol: TCP
            - port: "443"
              protocol: TCP
            - port: "80"
              protocol: TCP
    # Allow egress directly to zitadel in cluster
    - toEndpoints:
        - matchLabels:
            app.kubernetes.io/name: zitadel
            io.kubernetes.pod.namespace: zitadel
    - toEndpoints:
        - matchLabels:
            io.kubernetes.pod.namespace: kube-system
            k8s-app: kube-dns
      toPorts:
        - ports:
            - port: "53"
              protocol: UDP
