apiVersion: v1
kind: Secret
metadata:
  name: flux-vars
type: Opaque
stringData:
  IP_LB_CIDR: ENC[AES256_GCM,data:SDunthwESu1TrVk=,iv:8opRXS7SZtSDot97/zKcuRtysxVtUBotGFRjFsX+9y8=,tag:C3zZFm98gZ1fdhcQaeaj7A==,type:str]
  CILIUM_DEVICE: ENC[AES256_GCM,data:Qmc5wlQa,iv:7VvUykCwB6dcxxGOMt+bVCzOQ2vVOr7dc+rK2Lo6rT8=,tag:AipBBTJ7iBx9gh02d/IabA==,type:str]
  IP_CLUSTER_VIP: ENC[AES256_GCM,data:E4JYEWeCUxj9,iv:adBtTH3URwo3uhtQMdOH/2WcrI5TB5mL1g9k6mwJ0/c=,tag:YOZ0bmPK0NbODQZwy1TStw==,type:str]
sops:
  age:
    - recipient: age1yvl77vcj6cthafxqnjezrme4ntktjgd2j4xpgkcfutws83zrtdesk93cll
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6TkMrMndCZFpUY080VU9W
        NEZBNzJCdHFzbUN5RWFqdXJCdzFzMnF5UkFJCmlJOTNLZTM3MXlqWW15ekRicUhO
        cTI3M3hMbDlDRnhIU2dTbVRObEFlNGsKLS0tIE56Nm9maUtpY3hXUFdoUGs3eWkz
        VFMydnN4L1lMVGRZbVM5MFBwcG9DS1EKrttl/uy4yBjZp9p/1P6/USEHZSZAwTQ0
        YE2E0UYB9L6kxUj1RGizFIs7Xex3ODe/rWLjMjLj9F51+KoAehPtWg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-04T09:01:59Z"
  mac: ENC[AES256_GCM,data:BJCF2pnF92XrN6375Vklh3j9QWd64S0SShEo8+QUMbrGqbpbv9J6YH1Dx9NzuA7sSEiiW+YYxlVwzGB8i/k6rfX8EEryfI9r+LIUPk9QxfayqMViFHIKHm0XuF7yBsQuW6q1jxoRspJDHZTG/FtooixPhsVPXTyKzxeorkIJ2io=,iv:aQBoeSI74UI2YrA0YdIJlpBLl+3PEvxx911H6Tuo8rE=,tag:to8uT7TEfELn3OvaESkTCw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
