# ---
# # yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/cert-manager.io/certificate_v1.json
# apiVersion: cert-manager.io/v1
# kind: Certificate
# metadata:
#   name: unifi-tls
# spec:
#   secretName: unifi-tls
#   issuerRef:
#     name: letsencrypt-prodxs
#     kind: ClusterIssuer
#   dnsNames:
#     - unifi.x3y.space