# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/cilium.io/ciliumnetworkpolicy_v2.json
---
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: unifi
spec:
  description: "Network policy for UniFi Controller"
  endpointSelector:
    matchLabels:
      app.kubernetes.io/name: unifi
  ingress:
    # Allow same namespace traffic
    - fromEndpoints:
        - matchLabels:
            io.kubernetes.pod.namespace: home-system
    # Allow ingress from envoy-gateway
    - fromEndpoints:
        - matchLabels:
            io.kubernetes.pod.namespace: network
    # Allow unpoller from observability to scrape metrics
    - fromEndpoints:
        - matchLabels:
            io.kubernetes.pod.namespace: observability
      toPorts:
        - ports:
            - port: "8443"
              protocol: TCP
    # Allow UniFi device communication
    - fromEntities:
        - host
        - remote-node
        - world
      toPorts:
        - ports:
            - port: "8080"
              protocol: TCP
            - port: "3478"
              protocol: UDP
            - port: "10001"
              protocol: UDP
  egress:
    # Allow same namespace traffic
    - toEndpoints:
        - matchLabels:
            io.kubernetes.pod.namespace: home-system
    # Allow communication with UniFi devices
    - toEntities:
        - world
    # Allow DNS
    - toEndpoints:
        - matchLabels:
            io.kubernetes.pod.namespace: kube-system
            k8s-app: kube-dns
      toPorts:
        - ports:
            - port: "53"
              protocol: UDP
