apiVersion: gateway.networking.k8s.io/v1alpha2
kind: TLSRoute
metadata:
  name: unifi-route
spec:
  hostnames:
  - "unifi.${DOMAIN1}"
  parentRefs:
    - name: internal
      namespace: kube-system
  rules:
    # - matches:
    #     - path:
    #         type: PathPrefix
    #         value: /
    - backendRefs:
        - name: unifi
          port: 8443
