---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: envoy-ai-gateway
spec:
  chartRef:
    kind: OCIRepository
    name: envoy-ai-gateway
  dependsOn:
    - name: envoy-ai-gateway-crds
  interval: 1h
