---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: opentelemetry-operator
  namespace: flux-system
spec:
  targetNamespace: observability
  commonMetadata:
    labels:
      app.kubernetes.io/name: opentelemetry-operator
  dependsOn:
    - name: kube-prometheus-stack
      namespace: flux-system
  path: ./kubernetes/apps/observability/opentelemetry/operator
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-ops
  wait: true
  interval: 30m
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: opentelemetry-collector
  namespace: flux-system
spec:
  targetNamespace: observability
  commonMetadata:
    labels:
      app.kubernetes.io/name: opentelemetry-collector
  dependsOn:
    - name: opentelemetry-operator
      namespace: flux-system
  path: ./kubernetes/apps/observability/opentelemetry/collector
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-ops
  wait: true
  interval: 30m
