# apiVersion: networking.k8s.io/v1
# kind: Ingress
# metadata:
#   name: pg-default-rw
#   namespace: pg
# spec:
#   ingressClassName: ${INGRESS1}
#   rules:
#   - host: &host "pg-default-rw.${DOMAIN1}"
#     http:
#       paths:
#       - pathType: Prefix
#         path: "/"
#         backend:
#           service:
#             name: pg-default-rw
#             port:
#               number: 5432
#   tls:
#     - hosts:
#         - *host

---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: pg-default-rw
  # namespace: pg
spec:
  parentRefs:
    - name: envoy-internal
      namespace: network
  hostnames:
    - "pg-default-rw.${DOMAIN1}"
  rules:
    - backendRefs:
        - name: pg-default-rw
          port: 5432
