---
apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: &pg pg-default
spec:
  schedule: "0 0 0 * * *"
  immediate: true
  backupOwnerReference: self
  cluster:
    name: *pg
---
apiVersion: postgresql.cnpg.io/v1
kind: Backup
metadata:
  name: &pg pg-default
  namespace: pg
spec:
  cluster:
    name: *pg
#backup-1724181636