apiVersion: v1
kind: Secret
metadata:
    name: pg-default-s3
type: Opaque
stringData:
    #ENC[AES256_GCM,data:BRTBsPgv2kIpbu2ffjmM+F4L5/4V2MiGrL71+K+AtUi+7Xeoctjd7V1ovXh07F/DsHEOgqHs3BrTafa/xA==,iv:z/K6JG6NnBNKnhsiEjq6bz2uurfaZtJ3HJjyHDCF+/g=,tag:blrizULxXoRyl4c/UM9Cwg==,type:comment]
    #ENC[AES256_GCM,data:pY6eh+/UdARoE3ax5gStaVsZ9drFH8N+o2jsqzqURdbAZpF6JVNLgTcCzClVBqnS2h4Ck6jVO36rl2Vd7JTdtuaLHJH8,iv:CAcaYjaM3CPyTxswCBYNKatwpZQVe5ZqZvil/APz8SM=,tag:DvMzEL5P0uOTr6/U50qq4g==,type:comment]
    #ENC[AES256_GCM,data:6B7Ro0jEzrTs06/U4XKMz3n2kjVT6jFWP0uCxVzoOTQ7diinuBrd,iv:N5O59xtzu7tbAe5FWl8A08vt1a82/6xrnopUsyzuq6w=,tag:vlItEMnzYeGVsNR8kLloxg==,type:comment]
    #ENC[AES256_GCM,data:EGDSfHpgTM9HPwQHZt890hVoOYNVY+htOdq1QlzcXR8yF1/y0YS5TcLlJwwdoRc=,iv:VasyS/u1gz8LByKwdIcRyO8Ds4GVsRlN2ymH6IoN3s8=,tag:HG6RdmjJMhc7f7tQy+JQDA==,type:comment]
    #ENC[AES256_GCM,data:OSB1PJoz8N67HAlYLUSxVzW7a/wP4EZZJYZelXQ5pgpqGXSClXKTNJnyBg==,iv:PubxhdAxPWA7IOakHBTwIOWfURgxjyOlvo6dCfVGN3s=,tag:73TuC46o3YrVx83vowoagw==,type:comment]
    #ENC[AES256_GCM,data:32Z249tli2OEl0aoT94I+syquyFoFu0fIfT5CsWqAZgDDiyA06/l5OPKp/mVm+OSMAGZ,iv:T4UxFuo7UhpvqMY4Y9Dj29D7XyCKg2d48gPdmS2TvW0=,tag:BgtAVZqxYFNubcQ55MWDXA==,type:comment]
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:MB6TCdsFqBFR51OLmMLs1sMGpZ8=,iv:AHJJny/k8cZ9xNldMVvAr92YgyeFC84vQIWVrM/FpSU=,tag:xDw71i84lrO+UziBkbMj7A==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:vwoSt3C+rGqmbMkBTM6LmrZ/t+rwA3LjIiOkJFhFzZ5RpmpWGeSCOA==,iv:T18PmUUIQhoQxxTfVIbNwX/oVSCH+lnPWSzGqDgJC4Q=,tag:Dz8LOXofZt2pw2zz3Wg2AQ==,type:str]
sops:
    age:
        - recipient: age1yvl77vcj6cthafxqnjezrme4ntktjgd2j4xpgkcfutws83zrtdesk93cll
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwbTNQWmo1OUtqNFZ3M1N3
            K2NNaFQ1TWJTTUFxSmU2K3JUODlUSGt1OGlZCk1aZnlVcCs0dTdHcG8wSnBScmxV
            S0VyM2daUHdYYWV5QURlSEFZVlh2ZGMKLS0tIGpnWDQySGVkYjdCZWxjWWpnZTk2
            Z3VROWFNN3dCTGczWU45L1Fab1JZWmsKLDnvRDks2v0qmJ6/acywM0drvah3AjdN
            4fempLAxqdPKGae51fjP6X2j22CHH/uaUVfFlqh+ibeDpZJM7pYkFA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-13T05:46:55Z"
    mac: ENC[AES256_GCM,data:kjJmC1RJ3zmijTJigZlkbnZRraR+2720iudXYd/irYL3mLjFTpWqOH1VHE2Rr48thCC0uOj9v3N0km93De/MIyHtimh56zgCtkH67Oj0aYrkNChcPPoqZ/6f1QdXreMvlm4iSgYGZ6yYZ3fzNOBmQT70ipE5KVI9tOWqHCxVZds=,iv:m3AaqPhhbgRIpjuuVTte2H2+jONuJdHUa3FvqH64lG4=,tag:gD6EutIY4LIQRq0cnxb8IA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
