apiVersion: v1
kind: Secret
metadata:
    name: pg-default-s3
type: Opaque
stringData:
    #ENC[AES256_GCM,data:BRTBsPgv2kIpbu2ffjmM+F4L5/4V2MiGrL71+K+AtUi+7Xeoctjd7V1ovXh07F/DsHEOgqHs3BrTafa/xA==,iv:z/K6JG6NnBNKnhsiEjq6bz2uurfaZtJ3HJjyHDCF+/g=,tag:blrizULxXoRyl4c/UM9Cwg==,type:comment]
    #ENC[AES256_GCM,data:pY6eh+/UdARoE3ax5gStaVsZ9drFH8N+o2jsqzqURdbAZpF6JVNLgTcCzClVBqnS2h4Ck6jVO36rl2Vd7JTdtuaLHJH8,iv:CAcaYjaM3CPyTxswCBYNKatwpZQVe5ZqZvil/APz8SM=,tag:DvMzEL5P0uOTr6/U50qq4g==,type:comment]
    #ENC[AES256_GCM,data:6B7Ro0jEzrTs06/U4XKMz3n2kjVT6jFWP0uCxVzoOTQ7diinuBrd,iv:N5O59xtzu7tbAe5FWl8A08vt1a82/6xrnopUsyzuq6w=,tag:vlItEMnzYeGVsNR8kLloxg==,type:comment]
    #ENC[AES256_GCM,data:EGDSfHpgTM9HPwQHZt890hVoOYNVY+htOdq1QlzcXR8yF1/y0YS5TcLlJwwdoRc=,iv:VasyS/u1gz8LByKwdIcRyO8Ds4GVsRlN2ymH6IoN3s8=,tag:HG6RdmjJMhc7f7tQy+JQDA==,type:comment]
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:7M1nDJHw+Px52SerHkYhd7zqa+elYy0=,iv:B/r81XN7JWrKKOmhT8QpGxvV6bn9DqKDl+/oh6e+PtE=,tag:fHjol231VKC4U5L4Hd6JKg==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:ALVvogK5t9KP4U+5MibGtkvvcvuHpVpxZ4Ye,iv:z91k+QkE/6NUHp7flHPGySHCAUFLsd6M0ZMUoY0wcbQ=,tag:2PJCKqtp2jvFfl5yhc2z9w==,type:str]
sops:
    age:
        - recipient: age1yvl77vcj6cthafxqnjezrme4ntktjgd2j4xpgkcfutws83zrtdesk93cll
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwbTNQWmo1OUtqNFZ3M1N3
            K2NNaFQ1TWJTTUFxSmU2K3JUODlUSGt1OGlZCk1aZnlVcCs0dTdHcG8wSnBScmxV
            S0VyM2daUHdYYWV5QURlSEFZVlh2ZGMKLS0tIGpnWDQySGVkYjdCZWxjWWpnZTk2
            Z3VROWFNN3dCTGczWU45L1Fab1JZWmsKLDnvRDks2v0qmJ6/acywM0drvah3AjdN
            4fempLAxqdPKGae51fjP6X2j22CHH/uaUVfFlqh+ibeDpZJM7pYkFA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-18T05:33:36Z"
    mac: ENC[AES256_GCM,data:GuXmIGwM1nkRvvsFr8fUtO7sXHwGJLHXJytvD0JgV62N9OFj1vvnIJRVjUA1szDCdQon9buI/6fPJ50FVM/dazbGaolrErjUakSWvLbvU9cU5z2n9gFASDzWx3ciMvMA+iIUL2ZMck2ZmGzYiuTNLf1JYUw2iAMQWOmG5MvtOM0=,iv:iMxoCj6TPCP46k1Ubo3qyP7HUNqJ9e3FG8wmXzhPwW4=,tag:2p2bwIzWmfKFsKNZzlGVXg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
