apiVersion: v1
kind: Secret
metadata:
    name: pg-default-s3
type: Opaque
stringData:
    #ENC[AES256_GCM,data:BRTBsPgv2kIpbu2ffjmM+F4L5/4V2MiGrL71+K+AtUi+7Xeoctjd7V1ovXh07F/DsHEOgqHs3BrTafa/xA==,iv:z/K6JG6NnBNKnhsiEjq6bz2uurfaZtJ3HJjyHDCF+/g=,tag:blrizULxXoRyl4c/UM9Cwg==,type:comment]
    #ENC[AES256_GCM,data:pY6eh+/UdARoE3ax5gStaVsZ9drFH8N+o2jsqzqURdbAZpF6JVNLgTcCzClVBqnS2h4Ck6jVO36rl2Vd7JTdtuaLHJH8,iv:CAcaYjaM3CPyTxswCBYNKatwpZQVe5ZqZvil/APz8SM=,tag:DvMzEL5P0uOTr6/U50qq4g==,type:comment]
    #ENC[AES256_GCM,data:6B7Ro0jEzrTs06/U4XKMz3n2kjVT6jFWP0uCxVzoOTQ7diinuBrd,iv:N5O59xtzu7tbAe5FWl8A08vt1a82/6xrnopUsyzuq6w=,tag:vlItEMnzYeGVsNR8kLloxg==,type:comment]
    #ENC[AES256_GCM,data:EGDSfHpgTM9HPwQHZt890hVoOYNVY+htOdq1QlzcXR8yF1/y0YS5TcLlJwwdoRc=,iv:VasyS/u1gz8LByKwdIcRyO8Ds4GVsRlN2ymH6IoN3s8=,tag:HG6RdmjJMhc7f7tQy+JQDA==,type:comment]
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:QMcfEfFl7teoo4K4/0x4pBtxHxflB8o+AgmsFQ==,iv:W9icrkPgqCZQW/yJscAxMDHoH8yfAGSR2+JbZZN4x5I=,tag:9zRsC2EGaDSTzDlJ8P07xg==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:0ZZRbAPwLPlkRKe0sF/oHja5Po4JOki9/4etTUp1vZ4=,iv:3Syzg06VpAw9Lr5fsBheb1A+Rcj1M02Q1/ZfMDw2MxM=,tag:c+q7Fp6AEnEWLRYukMiGRw==,type:str]
    AWS_ACCESS_KEY_ID_CEPH: ENC[AES256_GCM,data:kAo7tH3Qf4mwHJ+xVwRw7CMmOiM=,iv:EPnAOAjNp/JXVTGQcWpZyhNPPRNTyfxgmzkE3rmWd2U=,tag:6X/kir1Y2RWQ5s4cLBKTvw==,type:str]
    AWS_SECRET_ACCESS_KEY_CEPH: ENC[AES256_GCM,data:z/+SCnptIvitiRnbNetOu5x7aIhjaklipFL7OoivTI0qUGuCXCJUUQ==,iv:5k5lWfHx/DSIB2cunDx1+G+JtRRWwWK8Q71g+4rMm5U=,tag:UiO9Vy+IEF5JvZTWBlDxdA==,type:str]
sops:
    age:
        - recipient: age1yvl77vcj6cthafxqnjezrme4ntktjgd2j4xpgkcfutws83zrtdesk93cll
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwbTNQWmo1OUtqNFZ3M1N3
            K2NNaFQ1TWJTTUFxSmU2K3JUODlUSGt1OGlZCk1aZnlVcCs0dTdHcG8wSnBScmxV
            S0VyM2daUHdYYWV5QURlSEFZVlh2ZGMKLS0tIGpnWDQySGVkYjdCZWxjWWpnZTk2
            Z3VROWFNN3dCTGczWU45L1Fab1JZWmsKLDnvRDks2v0qmJ6/acywM0drvah3AjdN
            4fempLAxqdPKGae51fjP6X2j22CHH/uaUVfFlqh+ibeDpZJM7pYkFA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-13T16:18:57Z"
    mac: ENC[AES256_GCM,data:OaBCW9NOJKM7/tHB3EiXyKUeceLq3JgszZ4VVATbDzydC8Of4o0rcDELnT0tRf4u2TKNCBvIFKygZVwzavj9SjIybqy5957Hsv6pXsc/0W9ufSPiSDDj3Qn/Q3hEZAQ71+D1XETh79i+kM38JIorGTTL84aXZnIH3xJ1HfykbrQ=,iv:o/FMw3p4dzceRjg5vLWf7WsB/omQwHbyO7GmsO5vJ18=,tag:FBMVkpeV6kZTuaf8/iKHvg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
