apiVersion: v1
kind: Secret
metadata:
    name: pg-default-superuser
type: Opaque
stringData:
    #ENC[AES256_GCM,data:yQvhMELwqhjVhwipfNOkPWtlG9fjk+0ZqJKcF/Q=,iv:0cM8peZ+C1Qw7DA24MTFhoWyj+27CfR/Yjqusr61PAE=,tag:YJXx5QFlZ8iyzAwfsf0KNA==,type:comment]
    username: ENC[AES256_GCM,data:Jwqksh5nuN3NsYCXLIZrB5gvrGKSSjBfBXlYyHou3tIq,iv:pEFyQZqme4ttdKnqNI5bzC3Njza7RJDjA356HJC4H5w=,tag:1FyvyTUXEdIb4hwUxzb1+A==,type:str]
    password: ENC[AES256_GCM,data:ZJap7RpXnygNogCavtXEuBNtwOusm9sT9MofdHZsTWaV+o51uQ==,iv:SSdZ8NwRbCSbfJ6E8vCAmcGOb0/JQJElsxX9yPgs7qc=,tag:puIrPW71mQo/uDZvk04zWw==,type:str]
sops:
    age:
        - recipient: age1yvl77vcj6cthafxqnjezrme4ntktjgd2j4xpgkcfutws83zrtdesk93cll
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWVXI2eGlpdG16RWs5NURG
            Wm9qb0FvUlh1NmZrcW5uTWVDZEVGUms2M0NJCnVuTytINTNwT2JCdERrM01rV05x
            SFl6R0JiVHZ4b0JKT3BmS0xhRng2MlkKLS0tIDM2WjlnZXhGTTZxNURXTndBMzRN
            dWVzemo1MEVrdnNTYnhkQzRXNlZaeFEKG1IR+F+epGXVW5Xl4ljGeLrHw6riS4+M
            DyzPuW9vaLQq9xXjMvqoV2JnaTuEXib7hlBIyCKMmA0Y6nHnvdE3RA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-18T05:33:41Z"
    mac: ENC[AES256_GCM,data:EuFPdsIQXOir+tb+gMgcTD3AFp+oc6SfajlT9fqrqKO8xyOdIkP1S702sWaGhWEThfV0RKRCro27WAzIRAA+IMxQ5khH+ybEdZbhpWNUQvX/JNgmD7nbIMcyAQaawdAXkKmXZBFM6l2Hvnwz9CLHCNziElwUoDZ400P0PzjZRsY=,iv:m2UdgWzzQkrdsFxG8FE7CooJ6lQaeUSKtnfQ7ROzROw=,tag:O4SDqtA+2qWSza0SRIrj/w==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
