---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/cert-manager.io/certificate_v1.json
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: domain1
spec:
  secretName: domain1-tls
  issuerRef:
    name: letsencrypt-prodxs
    kind: ClusterIssuer
  commonName: ${DOMAIN1}
  dnsNames:
    - ${DOMAIN1}
    - "*.${DOMAIN1}"
