---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: forejo
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: app-template
  values:
    controllers:
      forejo:
        annotations:
          reloader.stakater.com/auto: "true"
          vault.security.banzaicloud.io/vault-role: "default"
        initContainers:
          init-db:
            image:
              repository: ghcr.io/onedr0p/postgres-init
              tag: 16.4
            env:
              INIT_POSTGRES_DBNAME: forgejo
              INIT_POSTGRES_HOST: "vault:secret/data/pg_default#HOST"
              INIT_POSTGRES_USER: "vault:secret/data/pg_default#USER"
              INIT_POSTGRES_PASS: "vault:secret/data/pg_default#PASSWORD"
              INIT_POSTGRES_SUPER_PASS: "vault:secret/data/pg_default#PASSWORD"
        containers:
          app:
            image:
              repository: codeberg.org/forgejo/forgejo
              tag: 9.0.3
            env:
              FORGEJO__database__DB_TYPE: postgres
              FORGEJO__database__HOST: "vault:secret/data/pg_default#HOST"
              FORGEJO__database__NAME: forgejo
              FORGEJO__database__USER: "vault:secret/data/pg_default#USER"
              FORGEJO__database__PASSWD: "vault:secret/data/pg_default#PASSWORD"
              FORGEJO__security__INSTALL_LOCK: "true"
              FORGEJO__server__DOMAIN: "forejo.${DOMAIN1}"
              FORGEJO__server__ROOT_URL: "https://forejo.${DOMAIN1}/"
              FORGEJO__server__SSH_DOMAIN: "ssh.forejo.${DOMAIN1}"
              FORGEJO__server__SSH_PORT: "22"
              FORGEJO__server__SSH_LISTEN_PORT: "2222"
              # OIDC
              FORGEJO__auth__OIDC_SIGN_IN_TEXT: "Sign In with Ok8Sh"
              FORGEJO__auth__OIDC_ISSUER_URL: "${OAUTH2_ISSUER}"
              FORGEJO__auth__OIDC_CLIENT_ID:
                valueFrom:
                  secretKeyRef:
                    name: forgejo-oidc-creds
                    key: client_id
              FORGEJO__auth__OIDC_CLIENT_SECRET:
                valueFrom:
                  secretKeyRef:
                    name: forgejo-oidc-creds
                    key: client_secret
            resources:
              requests:
                cpu: 100m
                memory: 256Mi
              limits:
                memory: 512Mi
    service:
      app:
        controller: forejo
        ports:
          http:
            port: 3000
          ssh:
            port: 2222
    route:
      app:
        enabled: true
        parentRefs:
          - name: envoy-internal
            namespace: network
        hostnames:
          - "forejo.${DOMAIN1}"
        annotations:
          gethomepage.dev/enabled: "true"
          gethomepage.dev/name: Forejo
          gethomepage.dev/description: Self-hosted Git Service
          gethomepage.dev/group: Development
          gethomepage.dev/icon: forgejo.png
        rules:
          - backendRefs:
              - port: 3000
                name: forejo
    persistence:
      data:
        existingClaim: forgejo-data
        globalMounts:
          - path: /data
