apiVersion: v1
kind: Secret
metadata:
  name: forgejo-ssh-key
  namespace: dev-system
type: Opaque
stringData:
  id_ed25519.pub: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAILtDAy/op8G37UJCGV/mAE0m8B50Pw9FUp5aEDyNqkuI imerkle@github
