apiVersion: v1
kind: Secret
metadata:
  name: forgejo-oidc-creds
  namespace: dev-system
type: Opaque
stringData:
  client_id: "PLACEHOLDER"
  client_secret: "PLACEHOLDER"
---
apiVersion: v1
kind: Secret
metadata:
  name: forgejo-db-secret
  namespace: dev-system
type: Opaque
stringData:
  password: "PLACEHOLDER"
