# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/cilium.io/ciliumnetworkpolicy_v2.json
---
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: nats
spec:
  description: "Network policy for NATS"
  endpointSelector:
    matchLabels:
      app.kubernetes.io/name: nats
  ingress:
    # Allow same namespace traffic
    - fromEndpoints:
        - matchLabels:
            io.kubernetes.pod.namespace: db
    # Allow connections from app namespaces
    - fromEndpoints:
        - matchLabels:
            io.kubernetes.pod.namespace: home-system
        - matchLabels:
            io.kubernetes.pod.namespace: dev-system
        - matchLabels:
            io.kubernetes.pod.namespace: observability
      toPorts:
        - ports:
            - port: "4222"
              protocol: TCP
    # Allow cluster communication
    - fromEndpoints:
        - matchLabels:
            io.kubernetes.pod.namespace: db
      toPorts:
        - ports:
            - port: "6222"
              protocol: TCP
            - port: "8222"
              protocol: TCP
    # Allow prometheus scraping
    - fromEndpoints:
        - matchLabels:
            io.kubernetes.pod.namespace: observability
      toPorts:
        - ports:
            - port: "7777"
              protocol: TCP
  egress:
    # Allow same namespace traffic (cluster communication)
    - toEndpoints:
        - matchLabels:
            io.kubernetes.pod.namespace: db
    # Allow DNS
    - toEndpoints:
        - matchLabels:
            io.kubernetes.pod.namespace: kube-system
            k8s-app: kube-dns
      toPorts:
        - ports:
            - port: "53"
              protocol: UDP
