---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: "kyverno"
spec:
  chartRef:
    kind: OCIRepository
    name: kyverno
  values:
    crds:
      install: true
    customLabels:
      # netpols
      ingress.home.arpa/host: "allow"
      ingress.home.arpa/apiserver: "allow"
      egress.home.arpa/apiserver: "allow"
    backgroundController:
      rbac:
        clusterRole:
          extraResources:
            - apiGroups: [""]
              resources: ["pods"]
              verbs: ["create", "update", "patch", "delete", "get", "list"]
            - apiGroups: ["*"]
              resources: ["*"]
              verbs: ["*"]
    admissionController:
      replicas: 1
      rbac:
        clusterRole:
          extraResources:
            - apiGroups: [""]
              resources: ["pods"]
              verbs: ["create", "update", "delete"]
            - apiGroups: ["*"]
              resources: ["*"]
              verbs: ["*"]
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: "kubernetes.io/hostname"
          whenUnsatisfiable: "ScheduleAnyway"
          labelSelector:
            matchLabels:
              app.kubernetes.io/instance: "kyverno"
              app.kubernetes.io/component: "kyverno"