---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: 1-core-db-redis-app
  namespace: flux-system
spec:
  path: ./kube/deploy/core/db/redis/app
  dependsOn:
    - name: vault-app
---