---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: pg-vector-rw
spec:
  parentRefs:
    - name: internal
      namespace: kube-system
  hostnames:
    - "pg-vector-rw.${DOMAIN1}"
  rules:
    - backendRefs:
        - name: pg-vector-rw
          port: 5432
