---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: kopia
spec:
  # components:
  #   - ../../../../components/nfs-scaler
  dependsOn:
    - name: volsync
    - name: vault
      namespace: vault
  path: ./kubernetes/apps/volsync-system/kopia/app
  postBuild:
    substitute:
      APP: kopia
  targetNamespace: volsync-system
