apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-dns-secret
type: Opaque
stringData:
  CF_API_TOKEN: ENC[AES256_GCM,data:Nzz/qek18nE/CGDOH/0BIOMXuNtRFWnIY6n+QUUANCCiZDkKzqnQ,iv:TXzejhD6ZFnnCoKhLywSLJTvj332+kf48OpkZbrJybo=,tag:xtwwRowEkXltoYwhsRqgFw==,type:str]
  CF_ZONE_ID: ENC[AES256_GCM,data:XTvgbsgeHdv1VihJuTDkEsuVbVOkA9kyiT81Yq0cV12QvGzseN5CVcw=,iv:pf3xYcvS7CXGNcQMNczlG3BxCr4Plouij2wv1+X6T2o=,tag:zSmxykVn5xIeg7T84NrDCQ==,type:str]
sops:
  age:
    - recipient: age1yvl77vcj6cthafxqnjezrme4ntktjgd2j4xpgkcfutws83zrtdesk93cll
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3SVRQNTc4K0FGM01UUWxw
        d2FGTlRRZXlic2JSUkRFVk0rWnZER1NoS1FJCnVZUXpkRUVlTVBQZkZmdGxoanht
        NjB5WTY3cko2bGJmWWlCaGpMVFNTZzAKLS0tIDhDOWEvMUQvSTlCaVVRTHNEWXNl
        NDlBWnNiOEhpMm9kclUrbDdWMFJ6NGcKIJxNw3xmVs/aCVEVISacRb0RcZ0VMGsr
        heUvUyeS5AzxwWpWk+tnJ3fcUIx7ap0YiOqVzztOxCb2eiWJUMVKjw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-25T08:31:39Z"
  mac: ENC[AES256_GCM,data:VVO/ep3CmKeW5yK1HOh4CscpiDbGhoG/I7L3X1zq8UYDzusWjz6tI8T6UefQBb41r2IFe8VS0pBszvG2aFqGjtilOAak+v4a7Mw8ni6DHxYKXEBBrYfYRmF4uuiS4ES5/Gasm3GYqsmL5UHSaxzD7avY7N1S8Jow2Lc1wXCYc5k=,iv:B+7Us4fRrOFEz9IqOq9m0YcfEZ9eG5g2naOFJc7DobY=,tag:7+FUIO7P3MccRR1NP4RVqw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
