---
apiVersion: infra.contrib.fluxcd.io/v1alpha2
kind: Terraform
metadata:
  name: vaultwarden-zitadel-oidc
spec:
  interval: 1h
  approvePlan: auto
  path: ./terraform/zitadel-oidc

  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system

  vars:
    - name: app_name
      value: "vaultwarden"
    - name: redirect_uris
      value:
        - "https://vaultwarden.${DOMAIN1}/identity/connect/oidc-signin"

  writeOutputsToSecret:
    name: vaultwarden-oidc-creds
    outputs:
      - client_id
      - client_secret
