---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: home-system
metadata:
  labels:
    helm.flux.home.fluxvars: "true"
components:
  - ../../components/alerts
  - ../../components/repos
resources:
  - ./namespace.yaml
  # - ./vars.sops.yaml
  - ./unifi/ks.yaml
  - ./atuin/ks.yaml
  - ./syncthing/ks.yaml
  - ./home-assistant/ks.yaml
  - ./esphome/ks.yaml
  - ./pdf-tool/ks.yaml
  - ./rustdesk/ks.yaml
  - ./zealot/ks.yaml
