apiVersion: v1
kind: Secret
metadata:
  name: flux-vars
type: Opaque
stringData:
  PG_S3_FOLDER_PREV: ENC[AES256_GCM,data:9VAPDxSWWVppL3us,iv:favHkg3atIpJFmrNzA946d6GSe831e7sPsfUUTtq3Xw=,tag:vnebGSjfUG+zF64CTU2HPg==,type:str]
  PG_S3_FOLDER_CURR: ENC[AES256_GCM,data:I8IS/1v30IYrPzI8,iv:1rJ60bXgX+8m1NBPEwimQGDxM96TMQtSSq6qnw53wFQ=,tag:oNPZnyDte/W8DeP0VUQkjw==,type:str]
  S3_ENDPOINT: ENC[AES256_GCM,data:K37r9CvY71O/whnti5esinJluu9hXaPui09LcEpoSiqZvoWnhEE=,iv:MjyjA/BzBR6Vu7l2gjgl6AlkKgzD6hkGm3IqnkuwI64=,tag:sj8+mT+yihbJzrG5CPszIQ==,type:str]
sops:
  age:
    - recipient: age1yvl77vcj6cthafxqnjezrme4ntktjgd2j4xpgkcfutws83zrtdesk93cll
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVdzcwRUlNNGxvaGtzd2Za
        c2FFdkhjaGJZOXdBYmVYKy91cElIU2UzbUdJCjZZbVBiUjVLdjVqZVduVTB6UWZP
        K2EyUFYveVBqR0RPWTg3cjM1Z3NnWlkKLS0tIHpqTVBWQWRsMHVKRmVwekhCR1FS
        YW4yck5RMG93K2FJbWZzcHJvcEpnSmsKrcvA2/9Y9HDFIABAI9V126ONRW1wazcP
        fjaiAIlIkie78hcza40cYaphCFV+Wn6BDd5xgZdyUgpOZBSANqdY+A==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-04T10:19:24Z"
  mac: ENC[AES256_GCM,data:XoNFP2z3dJ012UYV5THeoaIOfa71mqcq3A1GFIJbEn8qxexbC39F4Aie9PdA9St/mPwiWsoLLKTQR346gvGFozzEa2M6RAWqHuG93zq+BJLvtfGmud6504HkODzYJWz5BarjPtGDfOSCtfie0H3TsqSQmLlK+9h8PAnkAMqVZjU=,iv:mDrehNg3ye0E/aSy1yzz9Sbxj9XCEx8uZxjZnXuxWlg=,tag:kiIDqgrWfr9zMHJb07TDUQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
