apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app kubevirt
  namespace: &namespace kubevirt
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  path: ./kubernetes/apps/kubevirt/kubevirt/app
  targetNamespace: *namespace