# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/cilium.io/ciliumnetworkpolicy_v2.json
---
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: mosquitto
spec:
  description: "Network policy for Mosquitto MQTT broker"
  endpointSelector:
    matchLabels:
      app.kubernetes.io/name: mosquitto
  ingress:
    # Allow same namespace traffic
    - fromEndpoints:
        - matchLabels:
            io.kubernetes.pod.namespace: db
    # Allow MQTT connections from home-system (home-assistant, esphome, etc)
    - fromEndpoints:
        - matchLabels:
            io.kubernetes.pod.namespace: home-system
      toPorts:
        - ports:
            - port: "1883"
              protocol: TCP
    # Allow external IoT devices via host network
    - fromEntities:
        - host
        - remote-node
      toPorts:
        - ports:
            - port: "1883"
              protocol: TCP
  egress:
    # Allow same namespace traffic
    - toEndpoints:
        - matchLabels:
            io.kubernetes.pod.namespace: db
    # Allow DNS
    - toEndpoints:
        - matchLabels:
            io.kubernetes.pod.namespace: kube-system
            k8s-app: kube-dns
      toPorts:
        - ports:
            - port: "53"
              protocol: UDP
