---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cliproxyapi
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: app-template
  values:
    controllers:
      cliproxyapi:
        annotations:
          reloader.stakater.com/auto: "true"
        pod:
          securityContext:
            runAsUser: 0
            # runAsGroup: 0
            # fsGroup: 0
            # fsGroupChangePolicy: "OnRootMismatch"
        containers:
          app:
            image:
              repository: eceasy/cli-proxy-api
              tag: latest
            env:
              TZ: America/New_York
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: false
              capabilities: { drop: ["ALL"], add: ["NET_BIND_SERVICE"] }
            resources:
              requests:
                cpu: 100m
                memory: 128Mi
              limits:
                memory: 256Mi
    service:
      app:
        controller: cliproxyapi
        ports:
          http:
            port: 8317
    route:
      app:
        enabled: true
        parentRefs:
          - name: envoy-internal
            namespace: network
        hostnames:
          - "cliproxyapi.${DOMAIN1}"
        rules:
          - backendRefs:
              - port: 8317
                name: cliproxyapi
    persistence:
      config:
        type: secret
        name: cliproxyapi-config
        globalMounts:
          - path: /CLIProxyAPI/config.yaml
            subPath: config.yaml
      auth:
        type: emptyDir
        globalMounts:
          - path: /root/.cli-proxy-api
