---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/gateway.networking.k8s.io/httproute_v1.json
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: hubble-ui
  annotations:
    gethomepage.dev/enabled: "true"
    gethomepage.dev/name: Hubble
    gethomepage.dev/description: Cilium Hubble UI
    gethomepage.dev/group: System
    gethomepage.dev/icon: hubble.png
spec:
  hostnames:
    - hubble.${DOMAIN1}
  parentRefs:
    - name: envoy-internal
      namespace: network
  rules:
    - backendRefs:
        - name: hubble-ui
          port: 80
