---
apiVersion: v1
kind: Secret
metadata:
  name: openai-secret
  namespace: network
type: Opaque
stringData:
  api-key: "vault:secret/data/ai#openai"
---
apiVersion: v1
kind: Secret
metadata:
  name: anthropic-secret
  namespace: network
type: Opaque
stringData:
  api-key: "vault:secret/data/ai#anthropic"
---
apiVersion: v1
kind: Secret
metadata:
  name: google-secret
  namespace: network
type: Opaque
stringData:
  api-key: "vault:secret/data/ai#google"
---
apiVersion: v1
kind: Secret
metadata:
  name: vercel-secret
  namespace: network
type: Opaque
stringData:
  api-key: "vault:secret/data/ai#vercel"
