---
apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: wan-net
spec:
  config: '{
      "cniVersion": "0.3.1",
      "name": "wan-net",
      "type": "macvlan",
      "master": "enp5s0",
      "mode": "bridge",
      "ipam": {}
    }'
---
apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: lan-net
spec:
  config: '{
      "cniVersion": "0.3.1",
      "name": "lan-net",
      "type": "macvlan",
      "master": "enp5s0",
      "mode": "bridge",
      "ipam": {}
    }'
