---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kubevirt.io/virtualmachine_v1.json
apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: openwrt
  labels:
    app.kubernetes.io/name: openwrt
spec:
  running: true
  template:
    metadata:
      labels:
        kubevirt.io/domain: openwrt
        kubevirt.io/vm: openwrt
    spec:
      domain:
        cpu:
          cores: 2
        devices:
          disks:
            - disk:
                bus: virtio
              name: containerdisk
            - disk:
                bus: virtio
              name: cloudinitdisk
          interfaces:
            - name: default
              masquerade: {}
            - name: wan
              macAddress: "02:00:00:00:00:01"
              bridge: {}
            - name: lan
              macAddress: "02:00:00:00:00:02"
              bridge: {}
        resources:
          requests:
            memory: 512Mi
      networks:
        - name: default
          pod: {}
        - name: wan
          multus:
            networkName: wan-net
        - name: lan
          multus:
            networkName: lan-net
      volumes:
        - name: containerdisk
          containerDisk:
            image: containercraft/openwrt:24
        - name: cloudinitdisk
          cloudInitNoCloud:
            userData: |-
              #cloud-config
              runcmd:
                - |
                  uci set network.wan.device='eth1'
                  uci set network.wan.proto='pppoe'
                  uci set network.wan.username='${OPENWRT_PPPOE_USER}'
                  uci set network.wan.password='${OPENWRT_PPPOE_PASS}'
                  uci set network.lan.device='eth2'
                  uci set network.lan.proto='static'
                  uci set network.lan.ipaddr='${OPENWRT_LAN_IP}'
                  uci set network.lan.netmask='${OPENWRT_LAN_NETMASK}'
                  uci set network.wan.peerdns='0'
                  uci del network.wan.dns
                  uci add_list network.wan.dns='1.1.1.1'
                  uci add_list network.wan.dns='1.0.0.1'
                  uci commit network
                  /etc/init.d/network restart
