apiVersion: gateway.networking.k8s.io/v1alpha2
kind: TLSRoute
metadata:
  name: vcluster-route
spec:
  hostnames:
  - "vcluster.x3y.space"
  parentRefs:
    - name: internal
      namespace: kube-system
      sectionName: tls
  rules:
    # - matches:
    #     - path:
    #         type: PathPrefix
    #         value: /
    - backendRefs:
        - name: vcluster
          port: 443
