apiVersion: gateway.networking.k8s.io/v1alpha3
kind: TLSRoute
metadata:
  name: vcluster-route
spec:
  hostnames:
  - "vcluster.${DNS_MAIN}"
  parentRefs:
    - name: internal
      namespace: kube-system
  rules:
    # - matches:
    #     - path:
    #         type: PathPrefix
    #         value: /
      backendRefs:
        - name: vcluster
          port: 443
