---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: zealot
spec:
  chartRef:
    kind: OCIRepository
    name: app-template
  interval: 15m
  values:
    controllers:
      zealot:
        containers:
          app:
            image:
              repository: tryzealot/zealot
              tag: latest
            env:
              PORT: &port 80
              ZEALOT_ADMIN_EMAIL: admin@admin.com
              ZEALOT_ADMIN_PASSWORD: password
              ZEALOT_DOMAIN: "{{ .Release.Name }}.${DOMAIN1}"
              ZEALOT_DATABASE_URL: "postgres://$${vault:secret/data/pg_default#USER}:$${vault:secret/data/pg_default#PASSWORD}@$${vault:secret/data/pg_default#HOST}:5432/zealot?sslmode=disable"
              SECRET_TOKEN: "85dbe15d75ef9308c7ae0f33c7a324cc6f4bf519a2ed2f3027bd33c140a4f9aa"
              SECRET_KEY_BASE: "85dbe15d75ef9308c7ae0f33c7a324cc6f4bf519a2ed2f3027bd33c140a4f9aa"
              DEFAULT_LOCALE: en
    service:
      app:
        controller: zealot
        ports:
          http:
            port: *port
    route:
      app:
        annotations:
          gethomepage.dev/enabled: "true"
          gethomepage.dev/name: Zealot
          gethomepage.dev/description: OTA Updates
          gethomepage.dev/group: Development
          gethomepage.dev/icon: zealot.png
        hostnames:
          - "{{ .Release.Name }}.${DOMAIN1}"
        parentRefs:
          - name: envoy-internal
            namespace: network
    persistence:
      config:
        existingClaim: "{{ .Release.Name }}"
      uploads:
        existingClaim: zealot-uploads
        globalMounts:
          - path: /app/public/uploads
