---
apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: wan-macvlan
spec:
  config: |
    {
      "cniVersion": "0.3.1",
      "name": "wan-macvlan",
      "type": "macvlan",
      "master": "enp5s0.100",
      "mode": "bridge",
      "ipam": {
        "type": "host-local",
        "ranges": [
          [ { "subnet": "169.254.100.0/24" } ]
        ]
      }
    }
---
apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: lan-macvlan
spec:
  config: |
    {
      "cniVersion": "0.3.1",
      "name": "lan-macvlan",
      "type": "macvlan",
      "master": "enp5s0",
      "mode": "bridge",
      "ipam": {
        "type": "host-local",
        "ranges": [
          [ { "subnet": "169.254.10.0/24" } ]
        ]
      }
    }
