---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app matrix
spec:
  targetNamespace: home-system
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  dependsOn:
    - name: rook-ceph-cluster
      namespace: rook-ceph
    - name: vault
      namespace: vault
  path: ./kubernetes/apps/home-system/matrix/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-ops
  wait: false
  interval: 30m
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: matrix-mautrix-whatsapp
spec:
  components:
    - ../../../../components/volsync
  targetNamespace: home-system
  commonMetadata:
    labels:
      app.kubernetes.io/name: mautrix-whatsapp
  dependsOn:
    - name: matrix
  path: ./kubernetes/apps/home-system/matrix/mautrix-whatsapp
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-ops
  wait: true
  interval: 30m
  postBuild:
    substitute:
      APP: mautrix-whatsapp
      VOLSYNC_CAPACITY: 1Gi
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: matrix-mautrix-telegram
spec:
  components:
    - ../../../../components/volsync
  targetNamespace: home-system
  commonMetadata:
    labels:
      app.kubernetes.io/name: mautrix-telegram
  dependsOn:
    - name: matrix
  path: ./kubernetes/apps/home-system/matrix/mautrix-telegram
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-ops
  wait: true
  interval: 30m
  postBuild:
    substitute:
      APP: mautrix-telegram
      VOLSYNC_CAPACITY: 1Gi
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: matrix-mautrix-slack
spec:
  components:
    - ../../../../components/volsync
  targetNamespace: home-system
  commonMetadata:
    labels:
      app.kubernetes.io/name: mautrix-slack
  dependsOn:
    - name: matrix
  path: ./kubernetes/apps/home-system/matrix/mautrix-slack
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-ops
  wait: true
  interval: 30m
  postBuild:
    substitute:
      APP: mautrix-slack
      VOLSYNC_CAPACITY: 1Gi
