---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: forgejo
  namespace: dev-system
spec:
  targetNamespace: dev-system
  interval: 1h
  path: ./kubernetes/apps/dev-system/forgejo/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  wait: true