---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: forgejo-oidc
  namespace: dev-system
spec:
  targetNamespace: dev-system
  interval: 1h
  path: ./kubernetes/apps/dev-system/forgejo/oidc
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  wait: true
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app forgejo
  namespace: dev-system
spec:
  dependsOn:
    - name: forgejo-oidc
  components:
    - ../../../../components/volsync
  targetNamespace: dev-system
  interval: 1h
  path: ./kubernetes/apps/dev-system/forgejo/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  wait: true
  postBuild:
    substitute:
      APP: *app
      VOLSYNC_CAPACITY: 5Gi
    substituteFrom:
      - kind: Secret
        name: forgejo-oidc-creds