---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: syncthing
  namespace: &ns home-system
spec:
  targetNamespace: *ns
  path: ./kubernetes/apps/home-system/syncthing/app
  dependsOn: []
  components:
    - ../../../../components/volsync
  postBuild:
    substitute:
      APP: syncthing
      VOLSYNC_CAPACITY: 5Gi