---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: syncthing-app
  namespace: &ns home-system
spec:
  targetNamespace: *ns
  path: ./kubernetes/apps/home-system/syncthing/app
  dependsOn: []
