---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: forejo
  namespace: flux-system
spec:
  targetNamespace: dev-system
  interval: 1h
  path: ./kubernetes/apps/dev-system/forejo/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  wait: true
  postBuild:
    substitute:
      DOMAIN1: x3y.space
      OAUTH2_ISSUER: https://hydra.x3y.space
