---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: forejo
  namespace: flux-system
spec:
  targetNamespace: dev-system
  interval: 1h
  path: ./kubernetes/apps/dev-system/forejo/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  wait: true
  dependsOn:
    - name: dev-system-code-server
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: flux-vars
