---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app telepresence
  namespace: &namespace dev-system
spec:
  targetNamespace: *namespace
  path: ./kubernetes/apps/dev-system/telepresence/app
  dependsOn: []
  postBuild:
    substitute:
      APP: *app
