apiVersion: v1
kind: Secret
metadata:
    name: flux-vars
type: Opaque
stringData:
    PG_S3_FOLDER_PREV: ENC[AES256_GCM,data:+BPb+cl9M+JEqxDs3Q==,iv:wPOtl3X4VslaJ8/dLNA7lMhljo0RBvqaUibfipvRZPU=,tag:l6jVeMeETj8yR1h7c2kfQQ==,type:str]
    PG_S3_FOLDER_CURR: ENC[AES256_GCM,data:5XB4x0x8OJtYzLF4Wg==,iv:pCTrTNe9SEXrqJ8qDmLoqK1d5dvFz30eAj4FL/mgEDo=,tag:4ZbZOt8Q/eRZsGA7VUFDSg==,type:str]
    S3_ENDPOINT: ENC[AES256_GCM,data:G1yX1zloz9lgvOi8DT8f8UmMTdvLllhkqbGxbZrlPbhHV2yn68Q=,iv:kFjb+QIHXA/iR4PQzomlk7kSxfhRY62wI/2i7eBXk84=,tag:tix3Vnt/yn/1igXXthn+6w==,type:str]
    VEC_PG_S3_FOLDER_PREV: ENC[AES256_GCM,data:1y5+v6k9od55WsQx,iv:kAJcEI8uh4U8ytPIN+qut7emQEIQJvljSGHpjfhUXH4=,tag:8iTBRKebaZyMy6n4iuxddA==,type:str]
    VEC_PG_S3_FOLDER_CURR: ENC[AES256_GCM,data:BGmxVGpwMBb7ZbWdjg==,iv:YB4uglmFa0pEOtR5qRzISVc/s4RVY/mWGqiFPGXr60c=,tag:vjaZ9tL82bDWcXqygf1c0Q==,type:str]
sops:
    age:
        - recipient: age1yvl77vcj6cthafxqnjezrme4ntktjgd2j4xpgkcfutws83zrtdesk93cll
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPTUVPa1JIOWNrNjJrc2h4
            L0hVZENwSHNHanhEelRBNGFEVzFKbXhjZ0djCmRDcUxDd29KYjlCWWpGTFQ5Qjlq
            SFdiTVkydHVZMTVxZEpNNlVQUDExUEkKLS0tIDcwYXVtWlRZQnZoMkIrWGszd0pO
            YzNXZkR0cTJDM3p5Z3lTRUliNkZqQ1EK8QEWCwKmKUlx+RtH0ouUVbcBTrxuq9FC
            wbUg8kv6lQ/HgFHaJI0Tux+jXUQgo/U+d9TVtaMyZ4GMAEnqGP/suw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-16T08:42:16Z"
    mac: ENC[AES256_GCM,data:r0pBHrgHjJ14czpKES9J/maIL+R0R56KJ5axIKAHMGfyEpP5AR66TPvkAlJpltgTOPl6XnXbJw+T+rFWxAtNQmvrHEsL/RAi2JEB0t4PXkpa47N3FOoC9mjraK3v7K+pihp7HTx0uymPUXEi2xHZWgMBISfmgFnTbZqJVALs1f0=,iv:8CQ+uPj4AmlFlKQ/62Tz95Dn2ixb3d8/i+ZxMjypC3Y=,tag:En3m5HGgnr2AfuAT0sqQEQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.11.0
