apiVersion: v1
kind: Secret
metadata:
    name: flux-vars
type: Opaque
stringData:
    PG_S3_FOLDER_PREV: ENC[AES256_GCM,data:5pYFpODgZ5OiH7n0,iv:HPQdP3fSwzX0emd+82N7Tl1519XxiPDYnPHYhXwBb8M=,tag:ineX4He491fs1ROLTdIB4g==,type:str]
    PG_S3_FOLDER_CURR: ENC[AES256_GCM,data:edfXBwtpEL3ChLw3Bw==,iv:PPEfvqZggSTO41jQWoU9Sz078WtQrM1gBRVtRYKwr4c=,tag:PPqpKHGUCvmSlFAHl2GaHQ==,type:str]
    S3_ENDPOINT: ENC[AES256_GCM,data:G1yX1zloz9lgvOi8DT8f8UmMTdvLllhkqbGxbZrlPbhHV2yn68Q=,iv:kFjb+QIHXA/iR4PQzomlk7kSxfhRY62wI/2i7eBXk84=,tag:tix3Vnt/yn/1igXXthn+6w==,type:str]
sops:
    age:
        - recipient: age1yvl77vcj6cthafxqnjezrme4ntktjgd2j4xpgkcfutws83zrtdesk93cll
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPTUVPa1JIOWNrNjJrc2h4
            L0hVZENwSHNHanhEelRBNGFEVzFKbXhjZ0djCmRDcUxDd29KYjlCWWpGTFQ5Qjlq
            SFdiTVkydHVZMTVxZEpNNlVQUDExUEkKLS0tIDcwYXVtWlRZQnZoMkIrWGszd0pO
            YzNXZkR0cTJDM3p5Z3lTRUliNkZqQ1EK8QEWCwKmKUlx+RtH0ouUVbcBTrxuq9FC
            wbUg8kv6lQ/HgFHaJI0Tux+jXUQgo/U+d9TVtaMyZ4GMAEnqGP/suw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-11T12:52:24Z"
    mac: ENC[AES256_GCM,data:7gClakmtelbfDwKCv5USM1r9fN8QJesXu4jgsPLgDj6rvy0+5mr5bw7GurBWvVptjmzTKNHAw+BUQXwyiQFsHq4sbYUzfRixhDbrw66OScvv1vMwFwnQtCc88EU1q5/gB1wz5apfZh/rAMuXULm7Wh1rarVOfdjMvqUoyE9035Q=,iv:u+1UCt4Xct+KlxJHf0dH2ruAijFOCVDAS6jHn0g6gAo=,tag:Wfff7qrJ0UlPt8FqgJ/+6Q==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.11.0
