apiVersion: v1
kind: Secret
metadata:
    name: login-client
type: Opaque
stringData:
    pat: ENC[AES256_GCM,data:ePEM5/vD+rxxThqb+3cDVXo4IUkUtgeVANhBjtJgAMhS2w/F/nZcA20k2qOpUuPxAehZHyWFwn34TyL9nkXxEkyyoNk+QvU=,iv:ANcdVxy0PmDnyX2xhGB3w/LyCBgOBFKdY8+oNUaB9Lo=,tag:yl/xreGE57HkbptF17cUmw==,type:str]
sops:
    age:
        - recipient: age1yvl77vcj6cthafxqnjezrme4ntktjgd2j4xpgkcfutws83zrtdesk93cll
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIV1dEK05iNU9tQ2xGNmFM
            YXRRUHpoQTMwRUNWd1VGMDhjaDVJSlZwQTI0CnZmSmF2TTQ5K2xTYWYxRytPSW4x
            TzIra2dJTXpjbUhJTVJHSzE2d2U4K2sKLS0tIFQrUVFNWDRpTGRQN2NVaXNVNzZB
            cituUlY4ZHhEczlDV2tsT0RPMUVCZ2MKn1jZcCpa6bGHhP9/XPs5IyK7XUY9HcEX
            w8S+jZSY03vytHO7gq1DqYl27L3C7OOo7ziEPH258WyvYrXb41+9Rg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-15T17:37:48Z"
    mac: ENC[AES256_GCM,data:V5UDBvGZsxG/wVICXAJMi3U5Vh1/vDBRFMVw/yUsS6hJnaPLjv0BuuWRQHRpUD3n6ow3S1ckDYOYAF6nHD8C29d2oin1wtkeCbHskHq0jpTXizQAkeCh29lz4rsvdJ6MfIrVcXEPpOFSmfayrVBiGrFOU6lw3TIOEUwXIPLpOXQ=,iv:TvfWuS5zuJA7gy8s2NCM1XxYiGvA5uUoQY7hp0mItoY=,tag:wZEs5Iy9Ky6fN+Aj8dbTGw==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.11.0
