---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: envoy-ai-gateway
spec:
  dependsOn:
    - name: envoy-gateway
  interval: 1h
  path: ./kubernetes/apps/network/envoy-ai-gateway/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: envoy-ai-gateway-system
  wait: false
