---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: stalwart
  namespace: home-system
spec:
  targetNamespace: home-system
  commonMetadata:
    labels:
      app.kubernetes.io/name: stalwart
  path: ./kubernetes/apps/home-system/stalwart/app
