---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/gateway.networking.k8s.io/httproute_v1.json
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: goldilocks
  annotations:
    gethomepage.dev/enabled: "true"
    gethomepage.dev/name: Goldilocks
    gethomepage.dev/description: Memory/CPU Recommendations Dashboard
    gethomepage.dev/group: Observability
    gethomepage.dev/icon: https://raw.githubusercontent.com/FairwindsOps/goldilocks/master/goldilocks_logo.png
spec:
  hostnames:
    - "goldilocks.${DOMAIN1}"
  parentRefs:
    - name: envoy-internal
      namespace: network
  rules:
    - backendRefs:
        - name: goldilocks-dashboard
          port: 80
