apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: db
components:
  - ../../components/alerts
  - ../../components/repos
resources:
  - namespace.yaml
  - pg/repo.yaml
  - pg/pg.sops.yaml
  - pg/ks.yaml
  - mosquitto/ks.yaml
  - dragonfly/ks.yaml

