apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: db
components:
  - ../../components/alerts
  - ../../components/repos
resources:
  - namespace.yaml
  - pg/repo.yaml
  # - pg/ns.yaml
  - pg/pg.sops.yaml
  - pg/ks.yaml

