# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/cilium.io/ciliumnetworkpolicy_v2.json
---
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: keda
spec:
  description: "Network policy for KEDA autoscaler"
  endpointSelector:
    matchLabels:
      app.kubernetes.io/instance: keda
  ingress:
    # Allow same namespace traffic
    - fromEndpoints:
        - matchLabels:
            io.kubernetes.pod.namespace: observability
    # Allow webhook from kube-apiserver
    - fromEntities:
        - kube-apiserver
  egress:
    # Allow same namespace traffic
    - toEndpoints:
        - matchLabels:
            io.kubernetes.pod.namespace: observability
    # Allow access to metrics sources in all namespaces
    - toEntities:
        - cluster
    # Allow kube-apiserver access
    - toEntities:
        - kube-apiserver
    # Allow external metrics sources
    - toEntities:
        - world
      toPorts:
        - ports:
            - port: "443"
              protocol: TCP
    # Allow DNS
    - toEndpoints:
        - matchLabels:
            io.kubernetes.pod.namespace: kube-system
            k8s-app: kube-dns
      toPorts:
        - ports:
            - port: "53"
              protocol: UDP
