---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: atuin
  namespace: &namespace home-system
spec:
  targetNamespace: *namespace
  dependsOn: []
  path: ./kubernetes/apps/home-system/atuin/app
  prune: true
  wait: false
