apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: pg-default-rw
spec:
  ingressClassName: ${INGRESS1}
  rules:
  - host: &host "pg-default-rw.${DOMAIN1}"
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: pg-default-rw
            port:
              number: 5432
  tls:
    - hosts:
        - *host
