apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
# - s3.yaml
- superuser.sops.yaml
- secret.sops.yaml
# - netpol.yaml
- cluster.yaml
# - scheduledbackup.yaml
# - ingress.yaml
# - dump-local.yaml
