apiVersion: v1
kind: Secret
metadata:
    name: pg-default-s3
    namespace: pg
type: Opaque
stringData:
    #ENC[AES256_GCM,data:BRTBsPgv2kIpbu2ffjmM+F4L5/4V2MiGrL71+K+AtUi+7Xeoctjd7V1ovXh07F/DsHEOgqHs3BrTafa/xA==,iv:z/K6JG6NnBNKnhsiEjq6bz2uurfaZtJ3HJjyHDCF+/g=,tag:blrizULxXoRyl4c/UM9Cwg==,type:comment]
    #ENC[AES256_GCM,data:pY6eh+/UdARoE3ax5gStaVsZ9drFH8N+o2jsqzqURdbAZpF6JVNLgTcCzClVBqnS2h4Ck6jVO36rl2Vd7JTdtuaLHJH8,iv:CAcaYjaM3CPyTxswCBYNKatwpZQVe5ZqZvil/APz8SM=,tag:DvMzEL5P0uOTr6/U50qq4g==,type:comment]
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:qisY3eHfkWEH1OO5D39kiw==,iv:drMW5LWKFdYaPg0JjXXdG5IUqnyODK2TgmmTilqrBm8=,tag:vf/TE2jb8dLNapx3U92G1A==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:U5Vaj2hxSYFCzCfxwaL6TmkXjCiZHTGCTMQOuBnZEKDXlqeQRapuzg==,iv:JgPA0NoDlpISCb4tQFIg8RV4Y5++73LjKjH1MbIhJho=,tag:Oz4gCQvu6k5SZrC317bOTw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1yvl77vcj6cthafxqnjezrme4ntktjgd2j4xpgkcfutws83zrtdesk93cll
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwbTNQWmo1OUtqNFZ3M1N3
            K2NNaFQ1TWJTTUFxSmU2K3JUODlUSGt1OGlZCk1aZnlVcCs0dTdHcG8wSnBScmxV
            S0VyM2daUHdYYWV5QURlSEFZVlh2ZGMKLS0tIGpnWDQySGVkYjdCZWxjWWpnZTk2
            Z3VROWFNN3dCTGczWU45L1Fab1JZWmsKLDnvRDks2v0qmJ6/acywM0drvah3AjdN
            4fempLAxqdPKGae51fjP6X2j22CHH/uaUVfFlqh+ibeDpZJM7pYkFA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-02-21T19:13:30Z"
    mac: ENC[AES256_GCM,data:hkTLJxlDT9+Y66+CibIsSRRnBru7TEEbGmefGhtEKb9GtYPT8SCITbhYam66ossEioc+Qk7IJtXv0igK7vRtqHQGKvMqulxE4pysJ8ndoGOJnJlCnFr/XhJvSDQVvpjQ1maVjyGN/27i9TfC7xBZtZiLyUEP1hjiSekeWRGDWeA=,iv:i4jat3SVuWUkdOGkKrzK/wlCPL9jvPjqSvGeWohHtk8=,tag:Efmi646kUuioIAKnGNN9UQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
