model_list:
  - model_name: "*"             # all requests where model not in your config go to this deployment
    litellm_params:
      model: antigravity/*           # set `openai/` to use the openai route
      api_key: your-api-key-here
      api_base: http://cliproxyapi:8317/v1
  # Google
  - model_name: Gemini-Flash
    litellm_params:
      model: gemini/gemini-3-flash-preview
      api_key: os.environ/GOOGLE_API_KEY

  - model_name: Gemini-Pro
    litellm_params:
      model: gemini/gemini-3-pro-preview
      api_key: os.environ/GOOGLE_API_KEY

  - model_name: Gemini-Image-Flash
    litellm_params:
      model: gemini/gemini-2.5-flash-image
      api_key: os.environ/GOOGLE_API_KEY
    model_info:
      mode: image_generation

  - model_name: Gemini-Image-Pro
    litellm_params:
      model: gemini/gemini-3-pro-image-preview
      api_key: os.environ/GOOGLE_API_KEY
    model_info:
      mode: image_generation

  # ChatMock
  - model_name: gpt-5-Mock
    litellm_params:
      model: openai/gpt-5
      api_base: http://chatmock:8000/v1
      api_key: sk-1234567890
  - model_name: gpt-5.1-Mock
    litellm_params:
      model: openai/gpt-5.1
      api_base: http://chatmock:8000/v1
      api_key: sk-1234567890
  - model_name: gpt-5.2-Mock
    litellm_params:
      model: openai/gpt-5.2
      api_base: http://chatmock:8000/v1
      api_key: sk-1234567890
  - model_name: gpt-5-codex-Mock
    litellm_params:
      model: openai/gpt-5-codex
      api_base: http://chatmock:8000/v1
      api_key: sk-1234567890
  - model_name: gpt-5.2-codex-Mock
    litellm_params:
      model: openai/gpt-5.2-codex
      api_base: http://chatmock:8000/v1
      api_key: sk-1234567890
  - model_name: gpt-5.1-codex-Mock
    litellm_params:
      model: openai/gpt-5.1-codex
      api_base: http://chatmock:8000/v1
      api_key: sk-1234567890
  - model_name: gpt-5.1-codex-max-Mock
    litellm_params:
      model: openai/gpt-5.1-codex-max
      api_base: http://chatmock:8000/v1
      api_key: sk-1234567890
  - model_name: gpt-5.1-codex-mini-Mock
    litellm_params:
      model: openai/gpt-5.1-codex-mini
      api_base: http://chatmock:8000/v1
      api_key: sk-1234567890
  - model_name: codex-mini-Mock
    litellm_params:
      model: openai/codex-mini
      api_base: http://chatmock:8000/v1
      api_key: sk-1234567890