model_list:
  - model_name: "qwen/*"
    litellm_params:
      model: "openai/*"
      api_key: your-api-key-here
      custom_llm_provider: "openai"
      api_base: http://cliproxyapi:8317/v1
  - model_name: "openai/*"
    litellm_params:
      model: "openai/*"
      api_key: your-api-key-here
      custom_llm_provider: "openai"
      api_base: http://cliproxyapi:8317/v1
  - model_name: "antigravity/*"
    litellm_params:
      model: "openai/*"
      api_key: your-api-key-here
      custom_llm_provider: "openai"
      api_base: http://cliproxyapi:8317/v1
  # Google
  - model_name: gemini/*
    litellm_params:
      model: gemini/*
      api_key: os.environ/GOOGLE_API_KEY


litellm_settings:
  check_provider_endpoint: true
general_settings:
  allow_model_discovery: true
  master_key: os.environ/LITELLM_MASTER_KEY

mcp_servers:
  "flux_mcp":
    url: "http://flux-operator-mcp.flux-system.svc.cluster.local:9090/mcp"
  "ha_mcp":
    url: "http://home-assistant.home-system.svc.cluster.local:8086/mcp"
  "context7":
    url: "https://mcp.context7.com/mcp"
    headers:
      CONTEXT7_API_KEY: "os.environ/CONTEXT7_API_KEY"