---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ocirepository.yaml
  - helmrelease.yaml
  - dnsendpoint.yaml
  - httproute.yaml
  - tailscale-auth-secret.yaml
patchesStrategicMerge:
  - patches/tailscale-sidecar.yaml
