---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ocirepository.yaml
  - helmrelease.yaml
  - dnsendpoint.yaml
  - httproute.yaml
  - tailscale-auth-secret.yaml
patches:
  - path: patches/tailscale-sidecar.yaml
    target:
      kind: StatefulSet
      name: stalwart-stalwart-mail
