---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/source.toolkit.fluxcd.io/ocirepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: stalwart
spec:
  interval: 1h
  url: oci://codeberg.org/wrenix/helm-charts/stalwart-mail
  ref:
    tag: 0.4.9
