---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: copyparty
spec:
  chart:
    spec:
      chart: app-template
      version: 2.4.0
      sourceRef:
        kind: OCIRepository
        name: app-template
        namespace: flux-system
  interval: 1h
  values:
    controllers:
      copyparty:
        containers:
          app:
            image:
              repository: copyparty/ac
              tag: latest
            resources:
              requests:
                cpu: 10m
                memory: 50Mi
              limits:
                memory: 512Mi
    service:
      app:
        controller: copyparty
        ports:
          http:
            port: 3923
    persistence:
      config:
        existingClaim: "{{ .Release.Name }}"
        globalMounts:
          - path: /cfg
          - path: /w
    route:
      app:
        annotations:
          gethomepage.dev/enabled: "true"
          gethomepage.dev/name: Copyparty
          gethomepage.dev/description: File Server
          gethomepage.dev/group: Storage
          gethomepage.dev/icon: folder-open
        hostnames:
          - "files.${DOMAIN1}"
        parentRefs:
          - name: envoy-internal
            namespace: network
