---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: copyparty
spec:
  chartRef:
    kind: OCIRepository
    name: app-template
  interval: 1h
  values:
    controllers:
      copyparty:
        containers:
          app:
            image:
              repository: copyparty/ac
              tag: latest
            resources:
              requests:
                cpu: 10m
                memory: 50Mi
              limits:
                memory: 512Mi
    service:
      app:
        controller: copyparty
        ports:
          http:
            port: 3923
    persistence:
      config:
        existingClaim: "{{ .Release.Name }}"
        globalMounts:
          - path: /cfg
          - path: /w
    route:
      app:
        annotations:
          gethomepage.dev/enabled: "true"
          gethomepage.dev/name: Copyparty
          gethomepage.dev/description: File Server
          gethomepage.dev/group: Storage
          gethomepage.dev/icon: folder-open
        hostnames:
          - "files.${DOMAIN1}"
        parentRefs:
          - name: envoy-internal
            namespace: network
