# GitHub Personal Access Token for MCP
# Create with: sops --encrypt --in-place secret.sops.yaml
apiVersion: v1
kind: Secret
metadata:
    name: github-mcp-token
type: Opaque
stringData:
    #ENC[AES256_GCM,data:/eV0kvY6ginhOqjfkKcX8Z6KKBCKYfgU9LB1MsR0YA==,iv:02iNn5syGZObHrZKItyZ8bWnVRMJDKl0liF1zlUtFz0=,tag:bsGgnVHZmeXVf2p03YjCBQ==,type:comment]
    apiKey: ENC[AES256_GCM,data:Bu51r1Phgvy9HBFZrPRDPhL5wQ9j6ycmPemRUDl9paC1s6aoUVzNpdX1Q5NwuHIOREQSt4R4kngw1k1O/ZhzZOdeDsA9rJI/9h2UlKVx8wN5pKKzhPHRd7ICImAs,iv:nUkokvQ01KM8En78jAITJR32xX5JDUC8FGAEhTY2UBs=,tag:kPvvRV6CRydIslxQi1sX5g==,type:str]
sops:
    age:
        - recipient: age1yvl77vcj6cthafxqnjezrme4ntktjgd2j4xpgkcfutws83zrtdesk93cll
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0U2lOc1NEeWlQakgwbFUw
            TU5sRHZXMHc5RGJGa0dOaDlna2pHYk9GODIwClZMYUdiVGJqMG52ZTNYQUYxeDg4
            QUlLRjA1dEZvVVhmYUx6OUMvWUMxb2MKLS0tIE55N3hpMmJOVThXa1RsVWMyd2hs
            WmdrZXdSUTFvVkdOcSsrSGxwaDhYVjAKPq6FIy6cBfhI98bzR5YjgackIQPa6Ymb
            C2OLo/ump8tW/InBqA7/Vwq1g8A9q6kLMMMW9Xpu8jBhEy0xuFX5gw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-05T21:45:19Z"
    mac: ENC[AES256_GCM,data:dFrQYErQLw2l71p7PLC8j7/nNTU8nd9Aa+Uodr10PYxZMbv8FakZB5TCEXe6H67uHifbVWFAcWdPiLjzVQFaM0GXs5VL8Ud6/tMVS8mTZtC02tVDHyRKreBBFjdq2EqKG+PZGJNFdVRQKzIGsnsuqAj3B8TR0naw3Bocrz/vvzE=,iv:TCTzXsCfAHW/r8rtFoUbAZBSKKJaH1I/l58hJVgwXcw=,tag:GmIWFL59mJgtuUJ9nu2gjA==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.11.0
