---
apiVersion: v1
kind: Secret
metadata:
  name: "${APP}-volsync-r2-secret"
type: Opaque
stringData:
  RESTIC_REPOSITORY: "s3:https://s3.us-west-002.backblazeb2.com/volsync69/${APP}"
  RESTIC_PASSWORD: "vault:secret/data/volsync#RESTIC_PASSWORD"
  AWS_ACCESS_KEY_ID: "vault:secret/data/volsync#S3_ACCESS_KEY_ID"
  AWS_SECRET_ACCESS_KEY: "vault:secret/data/volsync#S3_SECRET_ACCESS_KEY"