---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./helmrelease.yaml
  - ./netpol.yaml
  - ./pvc-media.yaml
configMapGenerator:
  - name: frigate-configmap
    files:
      - ./config/config.yml
  # - name: frigate-ptz-mosaic
  #   files:
  #     - ./config/ptz_mosaic.py
generatorOptions:
  disableNameSuffixHash: true
