---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./helmrelease.yaml
  - ./tofu.yaml
  - ./netpol.yaml
configMapGenerator:
  - name: frigate-configmap
    files:
      - ./config/config.yml
generatorOptions:
  disableNameSuffixHash: true
