---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: flux-mcp
  annotations:
    external-dns.alpha.kubernetes.io/hostname: flux-mcp.${DOMAIN1}
spec:
  parentRefs:
    - name: envoy-ai
      namespace: network
      kind: Gateway
      group: gateway.networking.k8s.io
  hostnames:
    - flux-mcp.${DOMAIN1}
  rules:
    - backendRefs:
        - name: flux-mcp-backend
          group: gateway.envoyproxy.io
          kind: Backend
