---
apiVersion: aigateway.envoyproxy.io/v1alpha1
kind: AIServiceBackend
metadata:
  name: flux-mcp-backend
spec:
  schema:
    name: OpenAI
  backendRef:
    name: flux-operator-mcp
    kind: Service
    port: 9090
