# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/cilium.io/ciliumnetworkpolicy_v2.json
---
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: snmp-exporter
spec:
  description: "Network policy for SNMP Exporter"
  endpointSelector:
    matchLabels:
      app.kubernetes.io/name: prometheus-snmp-exporter
  ingress:
    # Allow prometheus scraping
    - fromEndpoints:
        - matchLabels:
            io.kubernetes.pod.namespace: observability
      toPorts:
        - ports:
            - port: "9116"
              protocol: TCP
  egress:
    # Allow SNMP queries to network devices
    - toEntities:
        - world
      toPorts:
        - ports:
            - port: "161"
              protocol: UDP
    # Allow DNS
    - toEndpoints:
        - matchLabels:
            io.kubernetes.pod.namespace: kube-system
            k8s-app: kube-dns
      toPorts:
        - ports:
            - port: "53"
              protocol: UDP
