---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: litellm
  namespace: flux-system
spec:
  dependsOn: []
  interval: 1h
  path: ./kubernetes/apps/dev-system/litellm/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  targetNamespace: dev-system
  wait: false
