# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/cilium.io/ciliumnetworkpolicy_v2.json
---
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: element
spec:
  description: "Network policy for Element web client"
  endpointSelector:
    matchLabels:
      app.kubernetes.io/name: element
  ingress:
    # Allow ingress from envoy-gateway
    - fromEndpoints:
        - matchLabels:
            io.kubernetes.pod.namespace: network
  egress:
    # Allow traffic to Synapse
    - toEndpoints:
        - matchLabels:
            app.kubernetes.io/name: matrix-synapse
            io.kubernetes.pod.namespace: home-system
