---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cloudnative-pg
  namespace: cnpg
spec:
  chart:
    spec:
      chart: cloudnative-pg
      version: 0.21.6
      sourceRef:
        name: cloudnative-pg
        kind: HelmRepository
        namespace: flux-system
  values:
    crds:
      create: true
# ---
# apiVersion: helm.toolkit.fluxcd.io/v2
# kind: HelmRelease
# metadata:
#   name: &app crunchy-pgo
#   namespace: *app
# spec:
#   install:
#     crds: CreateReplace
#   upgrade:
#     crds: CreateReplace
#   chart:
#     spec:
#       chart: pgo
#       version: 5.4.2
#       sourceRef:
#         name: crunchydata
#         kind: HelmRepository
#         namespace: flux-system
