---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: 1-core-nats-app
  namespace: flux-system
spec:
  path: ./kube/deploy/core/db/nats/app
  dependsOn: []
  targetNamespace: nats
---

