---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: frigate
spec:
  components:
    - ../../../../components/volsync
  dependsOn:
    - name: rook-ceph-cluster
      namespace: rook-ceph
    - name: vault
      namespace: vault
  interval: 1h
  path: ./kubernetes/apps/home-system/frigate/app
  postBuild:
    substitute:
      APP: frigate
      VOLSYNC_CAPACITY: 5Gi
      DOMAIN1: x3y.space
      OIDC_PROVIDER_ID: 01HFVBY12TMNTYTBV8W921M5FB
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: home-system
  wait: false
