apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: ory
  namespace: ory
spec:
  interval: 5m
  url: https://k8s.ory.sh/helm/charts
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: oecis
  namespace: ory
spec:
  interval: 5m
  url: https://charts.oecis.io