apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: pvc-creator
  namespace: default
rules:
  - apiGroups: [""]
    resources: ["persistentvolumeclaims"]
    verbs: ["create", "get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: coder-pvc-binding
  namespace: default
subjects:
  - kind: ServiceAccount
    name: coder
    namespace: code-server
roleRef:
  kind: Role
  name: pvc-creator
  apiGroup: rbac.authorization.k8s.io
